### ISSUE TITLE
Deleting audio_features_visualization.ipynb ?

### ISSUE THREAD

**Issue by nadiaenh** [cpappas18/articulaite#13]
Should we delete audio_features_visualization.ipynb ? I feel like it's very hard to read and doesn't show any actual visualizations, and we already have feature_extraction.py, so it might be better to delete this one. Unless someone wants to clean it up ?

**Comment by RituA08** [comment]
Yeah I can clean it up so it only has the code to get the audio from the user and then the data visualization code?

**Comment by nadiaenh** [comment]
Okay cool !
